name: 'Islandora Metadata Vocabularies'
description: 'Starter taxonomy vocabularies for descriptive metadata.'
type: 'islandora'
install:
  - controlled_access_terms_defaults
config:
  import:
    controlled_access_terms_defaults:
      - core.entity_form_display.taxonomy_term.corporate_body.default
      - core.entity_form_display.taxonomy_term.family.default
      - core.entity_form_display.taxonomy_term.genre.default
      - core.entity_form_display.taxonomy_term.geo_location.default
      - core.entity_form_display.taxonomy_term.language.default
      - core.entity_form_display.taxonomy_term.person.default
      - core.entity_form_display.taxonomy_term.physical_form.default
      - core.entity_form_display.taxonomy_term.resource_types.default
      - core.entity_form_display.taxonomy_term.subject.default
      - core.entity_form_display.taxonomy_term.temporal_subjects.default
      - core.entity_view_display.taxonomy_term.corporate_body.default
      - core.entity_view_display.taxonomy_term.family.default
      - core.entity_view_display.taxonomy_term.genre.default
      - core.entity_view_display.taxonomy_term.geo_location.default
      - core.entity_view_display.taxonomy_term.language.default
      - core.entity_view_display.taxonomy_term.person.default
      - core.entity_view_display.taxonomy_term.physical_form.default
      - core.entity_view_display.taxonomy_term.resource_types.default
      - core.entity_view_display.taxonomy_term.subject.default
      - core.entity_view_display.taxonomy_term.temporal_subjects.default
      - field.field.taxonomy_term.corporate_body.field_authority_link
      - field.field.taxonomy_term.corporate_body.field_cat_date_begin
      - field.field.taxonomy_term.corporate_body.field_cat_date_end
      - field.field.taxonomy_term.corporate_body.field_corp_alt_name
      - field.field.taxonomy_term.corporate_body.field_relationships
      - field.field.taxonomy_term.corporate_body.field_type
      - field.field.taxonomy_term.family.field_authority_link
      - field.field.taxonomy_term.family.field_cat_date_begin
      - field.field.taxonomy_term.family.field_cat_date_end
      - field.field.taxonomy_term.family.field_relationships
      - field.field.taxonomy_term.genre.field_authority_link
      - field.field.taxonomy_term.geo_location.field_authority_link
      - field.field.taxonomy_term.geo_location.field_geo_alt_name
      - field.field.taxonomy_term.geo_location.field_geo_broader
      - field.field.taxonomy_term.geo_location.field_geo_geolocation
      - field.field.taxonomy_term.language.field_authority_link
      - field.field.taxonomy_term.person.field_alternate_name
      - field.field.taxonomy_term.person.field_authority_link
      - field.field.taxonomy_term.person.field_cat_date_begin
      - field.field.taxonomy_term.person.field_cat_date_end
      - field.field.taxonomy_term.person.field_relationships
      - field.field.taxonomy_term.physical_form.field_authority_link
      - field.field.taxonomy_term.resource_types.field_authority_link
      - field.field.taxonomy_term.subject.field_authority_link
      - field.field.taxonomy_term.temporal_subjects.field_authority_link
      - field.storage.taxonomy_term.field_alternate_name
      - field.storage.taxonomy_term.field_authority_link
      - field.storage.taxonomy_term.field_cat_date_begin
      - field.storage.taxonomy_term.field_cat_date_end
      - field.storage.taxonomy_term.field_corp_alt_name
      - field.storage.taxonomy_term.field_geo_alt_name
      - field.storage.taxonomy_term.field_geo_broader
      - field.storage.taxonomy_term.field_geo_geolocation
      - field.storage.taxonomy_term.field_relationships
      - field.storage.taxonomy_term.field_type
      - language.content_settings.taxonomy_term.corporate_body
      - language.content_settings.taxonomy_term.family
      - language.content_settings.taxonomy_term.genre
      - language.content_settings.taxonomy_term.geo_location
      - language.content_settings.taxonomy_term.language
      - language.content_settings.taxonomy_term.person
      - language.content_settings.taxonomy_term.physical_form
      - language.content_settings.taxonomy_term.resource_types
      - language.content_settings.taxonomy_term.subject
      - language.content_settings.taxonomy_term.temporal_subjects
      - taxonomy.vocabulary.corporate_body
      - taxonomy.vocabulary.family
      - taxonomy.vocabulary.genre
      - taxonomy.vocabulary.geo_location
      - taxonomy.vocabulary.language
      - taxonomy.vocabulary.person
      - taxonomy.vocabulary.physical_form
      - taxonomy.vocabulary.resource_types
      - taxonomy.vocabulary.subject
      - taxonomy.vocabulary.temporal_subjects
